url: http://www.makercamp.io
baseurl: /makercamp.io

# Site settings
title: Makercamp Shenzhen
email: info@makercamp.io
description: "Work with other hardware hackers and find a manufacturer for your awesome project."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1E824C
  secondary: 1E824C  
  secondary-dark: 1E824C
  title: 2ECC71

# Team names, titles and social links
people:
- name: Jaysen
  pic: 2
  position: Serial Web Entrepreneur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Scotty
  pic: 2
  position: Long-time hardware hacker
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Manu
  pic: 2
  position: Supply Chainer, IT Entrepreneur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Fabio
  pic: 2
  position: China Sourcing Specialist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty